version: '3.8'

services:
  puppeteer-scraper:
    build: .
    container_name: puppeteer-scraper-with-subpages
    environment:
      - NODE_ENV=production
      - MAX_DEPTH=2
      - MAX_PAGES=20
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1.0'
    restart: unless-stopped
